### ISSUE TITLE
Слайдер

### ISSUE THREAD

**Issue by danilsizov** [danilsizov/Odessa-dress-shop#1]
1. Первый слайдер - прокрутка в стороны, стрелки
2. Слайдер в самых популярных товарах. Прокрутка вверх, фото обрезать.
3. Слайдер там же, прокрутка в сторону.

**Comment by flaminisx** [comment]
"фото обрезать" - подробнее можно?

**Comment by danilsizov** [comment]
Фотографии в этом слайдере вытянутые, ширины намного больше чем высота, а входящие фото будут наоборот - высота значительно больше, необходимо по центру обрезать, сейчас можно этого не делать, но потом должно быть

**Comment by flaminisx** [comment]
для слайдеров не хватает пары стрелок.
нада залить файлы
image/top-slider-arrow-left.png и
image/top-slider-arrow-right-hover.png

**Comment by flaminisx** [comment]
сделал карусель.
осталось залить картинки...
